defaults:
  - _commons
  - _commons_bnlearn
  - _self_

_target_: torch_concepts.data.datamodules.bnlearn.BnLearnDataModule

name: barley

default_task_names: [s2528]

autoencoder_kwargs:
  latent_dim: 128