defaults:
  - _default
  - _self_

hydra:
  job:
    name: test
  sweeper:
    params:
      seed: 42
      dataset: insurance
      model: blackbox
      loss: standard

dataset:
  batch_size: 4096

model:
  optim_kwargs:
    lr: 0.01
  latent_encoder_kwargs:
    hidden_size: 128
    n_layers: 3
    activation: leaky_relu
    dropout: 0.1

metrics:
  summary_metrics: false
  perconcept_metrics: true #${dataset.default_task_names}

trainer:
  # logger: wandb
  max_epochs: 2000
  patience: 50

matmul_precision: medium

notes: test_blackbox